
package vista;

import controlador.LibroDAO;
import modelo.Libro;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class ConsultarLibrosUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarLibrosUsuario.class.getName());

    /**
     * Creates new form ConsultarLibrosUsuario
     */
    public ConsultarLibrosUsuario() {
    initComponents();
    configurarBtnAyuda();
    
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblLibrosDisponibles);
    EstiloUI.estilizarBotonPrimario(btnCargarLibros);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.configurarBtnVolver(btnAtras, this);
    EstiloUI.estilizarBotonSecundario(btnAtras);
    
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibrosDisponibles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosDisponibles = new javax.swing.JTable();
        btnCargarLibros = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLibrosDisponibles.setText("LIBROS DISPONIBLES");

        tblLibrosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Autor", "Año", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosDisponibles);

        btnCargarLibros.setText("Mostrar Libros Disponibles");
        btnCargarLibros.addActionListener(this::btnCargarLibrosActionPerformed);

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");
        btnAyuda.addActionListener(this::btnAyudaActionPerformed);

        btnAtras.setText("<-");
        btnAtras.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLibrosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAyuda)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnCargarLibros)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibrosDisponibles)
                    .addComponent(btnAyuda)
                    .addComponent(btnAtras))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarLibros)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLibrosActionPerformed
        // TODO add your handling code here:
        LibroDAO dao = new LibroDAO();

        List<Libro> libros =
        dao.obtenerLibrosDisponibles();

        DefaultTableModel modelo =
        (DefaultTableModel)
        tblLibrosDisponibles.getModel();

        modelo.setRowCount(0);

        for (Libro libro : libros) {

        modelo.addRow(new Object[]{

        libro.getId(),
        libro.getTitulo(),
        libro.getAutor(),
        libro.getAnioPublicacion(),
        libro.getEstado()

        });
        }
    }//GEN-LAST:event_btnCargarLibrosActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    mostrarAyuda();

    }//GEN-LAST:event_btnAyudaActionPerformed

    private void configurarBtnAyuda() {
    btnAyuda.setBackground(new java.awt.Color(70, 130, 180));
    btnAyuda.setForeground(java.awt.Color.WHITE);
    btnAyuda.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
    btnAyuda.setFocusPainted(false);
    btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // Estilo y acción btnAtras
    btnAtras.setBackground(new java.awt.Color(100, 100, 100));
    btnAtras.setForeground(java.awt.Color.WHITE);
    btnAtras.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnAtras.setFocusPainted(false);
    btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAtras.setText("←");
    btnAtras.addActionListener(e -> dispose());
    }

    private void mostrarAyuda() {
    String contenido =
        "<html><body style='font-family:SansSerif; padding:8px'>"
        + "<h3 style='color:#2c6fad'> LIBROS DISPONIBLES</h3>"
        + "<hr>"
        + "<p>Esta pantalla muestra todos los libros disponibles "
        + "para préstamo en la biblioteca.</p>"
        + "<br>"
        + "<p>La tabla muestra la siguiente información de cada libro:</p>"
        + "<ul>"
        + "<li><b>ID</b> — Número identificador del libro.</li>"
        + "<li><b>Título</b> — Nombre del libro.</li>"
        + "<li><b>Autor</b> — Nombre del autor.</li>"
        + "<li><b>Año</b> — Año de publicación.</li>"
        + "<li><b>Estado</b> — Estado actual (DISPONIBLE).</li>"
        + "</ul>"
        + "<br>"
        + "<p>▶ Presiona <b>Mostrar Libros Disponibles</b> para "
        + "cargar o actualizar la lista.</p>"
        + "</body></html>";

    javax.swing.JLabel lbl = new javax.swing.JLabel(contenido);
    lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

    javax.swing.JOptionPane.showMessageDialog(
        this, lbl,
        "Ayuda — Libros Disponibles",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarLibrosUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCargarLibros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLibrosDisponibles;
    private javax.swing.JTable tblLibrosDisponibles;
    // End of variables declaration//GEN-END:variables
}
