
package vista;

import controlador.PersonaDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Persona;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class GestionUsuarios extends javax.swing.JFrame {
    
    
    private boolean esBibliotecario = false;
    private boolean passwordVisible = false;
    private boolean passwordCVisible = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionUsuarios.class.getName());

    
    public GestionUsuarios() {
    initComponents();

    configurarBtnAyuda(); // ← reemplaza el bloque largo
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());

    btnVolver.setBackground(new java.awt.Color(100, 100, 100));
    btnVolver.setForeground(java.awt.Color.WHITE);
    btnVolver.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnVolver.setFocusPainted(false);
    btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());

    aplicarEstilos(); 
    
    // Estilo btnMostrar
    btnMostrar.setText("👁");
    btnMostrar.setFont(new Font("SansSerif", Font.PLAIN, 12));
    btnMostrar.setPreferredSize(new Dimension(34, 26));
    btnMostrar.setFocusPainted(false);
    btnMostrar.setBackground(new Color(52, 120, 200));
    btnMostrar.setForeground(Color.WHITE);
    btnMostrar.setBorderPainted(false);
    btnMostrar.setCursor(new Cursor(Cursor.HAND_CURSOR));

    // Estilo btnMostrarC
    btnMostrarC.setText("👁");
    btnMostrarC.setFont(new Font("SansSerif", Font.PLAIN, 12));
    btnMostrarC.setPreferredSize(new Dimension(34, 26));
    btnMostrarC.setFocusPainted(false);
    btnMostrarC.setBackground(new Color(52, 120, 200));
    btnMostrarC.setForeground(Color.WHITE);
    btnMostrarC.setBorderPainted(false);
    btnMostrarC.setCursor(new Cursor(Cursor.HAND_CURSOR));


    btnMostrar.addActionListener(e -> {
    passwordVisible = !passwordVisible;
    if (passwordVisible) {
        txtPassword.setEchoChar((char) 0);
        btnMostrar.setText("🙈");
    } else {
        txtPassword.setEchoChar('\u2022');
        btnMostrar.setText("👁");
    }
    txtPassword.requestFocus();
    });


    btnMostrarC.addActionListener(e -> {
    passwordCVisible = !passwordCVisible;
    if (passwordCVisible) {
        txtPasswordActualizar.setEchoChar((char) 0);
        btnMostrarC.setText("🙈");
    } else {
        txtPasswordActualizar.setEchoChar('\u2022');
        btnMostrarC.setText("👁");
    }
    txtPasswordActualizar.requestFocus();
    });

    
    setLocationRelativeTo(null);
    }
    
    public GestionUsuarios(boolean esBibliotecario) {
    initComponents();

    this.esBibliotecario = esBibliotecario;
    configurarBtnAyuda();

    btnVolver.setBackground(new java.awt.Color(100, 100, 100));
    btnVolver.setForeground(java.awt.Color.WHITE);
    btnVolver.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnVolver.setFocusPainted(false);
    btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());

    if (esBibliotecario) {
        cmbRol.removeAllItems();
        cmbRol.addItem("USUARIO");
        cmbRolActualizar.removeAllItems();
        cmbRolActualizar.addItem("USUARIO");
        cmbRolEliminar.removeAllItems();
        cmbRolEliminar.addItem("USUARIO");
    }

    aplicarEstilos();
    
    // Mostrar/ocultar contraseña Registrar
btnMostrar.setText("Ver");
btnMostrar.addActionListener(e -> {
    if (txtPassword.getEchoChar() != (char) 0) {
        // está oculta → mostrar
        txtPassword.setEchoChar((char) 0);
        btnMostrar.setText("Ocultar");
    } else {
        // está visible → ocultar
        txtPassword.setEchoChar('\u2022'); // bullet point •
        btnMostrar.setText("Ver");
    }
});

// Mostrar/ocultar contraseña Actualizar
btnMostrarC.setText("Ver");
btnMostrarC.addActionListener(e -> {
    if (txtPasswordActualizar.getEchoChar() != (char) 0) {
        txtPasswordActualizar.setEchoChar((char) 0);
        btnMostrarC.setText("Ocultar");
    } else {
        txtPasswordActualizar.setEchoChar('\u2022');
        btnMostrarC.setText("Ver");
    }
});
    
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGestionRegistro = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        cmbRol = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        lblRolRegistrar = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1Cedula = new javax.swing.JLabel();
        txtBuscarCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblCedulaEliminar = new javax.swing.JLabel();
        lblNombreEliminar = new javax.swing.JLabel();
        lblUsuarioEliminar = new javax.swing.JLabel();
        lblRolEliminar = new javax.swing.JLabel();
        txtBuscarCedulaEliminar = new javax.swing.JTextField();
        txtUsuarioEliminar = new javax.swing.JTextField();
        txtNombreEliminar = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        cmbRolEliminar = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblCedulaActualizar = new javax.swing.JLabel();
        txtCedulaActualizar = new javax.swing.JTextField();
        btnBuscarActualizar = new javax.swing.JButton();
        lblNombreActualizar = new javax.swing.JLabel();
        lblApellidoActualizar = new javax.swing.JLabel();
        lblTelefonoActualizar = new javax.swing.JLabel();
        lblEmailActualizar = new javax.swing.JLabel();
        lblUsernameActualizar = new javax.swing.JLabel();
        lblPasswordActualizar = new javax.swing.JLabel();
        txtTelefonoActualizar = new javax.swing.JTextField();
        txtNombreActualizar = new javax.swing.JTextField();
        txtApellidoActualizar = new javax.swing.JTextField();
        txtEmailActualizar = new javax.swing.JTextField();
        txtUsernameActualizar = new javax.swing.JTextField();
        txtPasswordActualizar = new javax.swing.JPasswordField();
        cmbRolActualizar = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        lblRolActualizar = new javax.swing.JLabel();
        btnMostrarC = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGestionRegistro.setText("Gestión de Registro");

        lblCedula.setText("Cédula* :");

        lblNombre.setText("Nombre* :");

        lblApellido.setText("Apellido* :");

        lblTelefono.setText("Teléfono* :");

        lblEmail.setText("Email* :");

        lblUsuario.setText("Usuario* :");

        lblContraseña.setText("Contraseña* :");

        txtPassword.setText("jPasswordField1");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "BIBLIOTECARIO" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblRolRegistrar.setText("Rol* :");

        btnMostrar.setText("Ver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRolRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrar))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRolRegistrar))))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar", jPanel1);

        jLabel1Cedula.setText("Cédula* :");

        txtBuscarCedula.addActionListener(this::txtBuscarCedulaActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Usuario", "Rol"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Cedula)
                    .addComponent(txtBuscarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel3);

        lblCedulaEliminar.setText("Cédula* :");

        lblNombreEliminar.setText("Nombre :");

        lblUsuarioEliminar.setText("Usuario :");

        lblRolEliminar.setText("Rol :");

        txtUsuarioEliminar.setEnabled(false);

        txtNombreEliminar.setEnabled(false);

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(this::btnBuscarEliminarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        cmbRolEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "BIBLIOTECARIO" }));
        cmbRolEliminar.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCedulaEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombreEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(lblUsuarioEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRolEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtBuscarCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsuarioEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(cmbRolEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(38, 38, 38)
                        .addComponent(btnBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaEliminar)
                    .addComponent(txtBuscarCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminar))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEliminar)
                    .addComponent(txtNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioEliminar)
                    .addComponent(txtUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRolEliminar)
                    .addComponent(cmbRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnEliminar)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel5);

        lblCedulaActualizar.setText("Cédula* :");

        btnBuscarActualizar.setText("Buscar");
        btnBuscarActualizar.addActionListener(this::btnBuscarActualizarActionPerformed);

        lblNombreActualizar.setText("Nombre :");

        lblApellidoActualizar.setText("Apellido :");

        lblTelefonoActualizar.setText("Teléfono :");

        lblEmailActualizar.setText("Email :");

        lblUsernameActualizar.setText("Usuario :");

        lblPasswordActualizar.setText("Contraseña :");

        txtPasswordActualizar.setText("jPasswordField1");

        cmbRolActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "BIBLIOTECARIO" }));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        lblRolActualizar.setText("Rol :");

        btnMostrarC.setText("Ver");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCedulaActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblTelefonoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApellidoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRolActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCedulaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBuscarActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEmailActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtApellidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUsernameActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtTelefonoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblPasswordActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cmbRolActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtUsernameActualizar)
                            .addComponent(txtPasswordActualizar)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnMostrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaActualizar)
                    .addComponent(txtCedulaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarActualizar))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreActualizar)
                    .addComponent(lblEmailActualizar)
                    .addComponent(txtEmailActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(lblApellidoActualizar)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUsernameActualizar)
                                .addComponent(txtUsernameActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtApellidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoActualizar)
                    .addComponent(txtTelefonoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordActualizar)
                    .addComponent(txtPasswordActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarC))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRolActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addComponent(lblRolActualizar))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar", jPanel4);

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        btnVolver.setText("<-");
        btnVolver.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(lblGestionRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionRegistro)
                    .addComponent(btnAyuda)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedula.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String telefono = txtTelefono.getText();
        String email = txtEmail.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String rol = cmbRol.getSelectedItem().toString();

        Persona persona = new Persona(
        0,
        cedula,
        nombre,
        apellido,
        telefono,
        email,
        username,
        password,
        rol
        );

        PersonaDAO dao = new PersonaDAO();

        if (dao.guardarPersona(persona)) {

        JOptionPane.showMessageDialog(
            this,
            "Usuario registrado correctamente"
        );
        
        limpiarCampos();
        
        } else {

        JOptionPane.showMessageDialog(
            this,
            "Error al registrar usuario"
        );
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCedulaActionPerformed
        // TODO add your handling code here:
        String cedula = txtBuscarCedula.getText();

    PersonaDAO dao = new PersonaDAO();

    Persona persona = dao.buscarPorCedula(cedula);

    if (persona != null) {

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Cédula");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Usuario");
    modelo.addColumn("Rol");

    modelo.addRow(new Object[]{
        persona.getCedula(),
        persona.getNombre(),
        persona.getApellido(),
        persona.getUsername(),
        persona.getRol()
    });

    tblUsuarios.setModel(modelo);

    } else {

    JOptionPane.showMessageDialog(
            this,
            "No se encontró el usuario"
    );
    }
    }//GEN-LAST:event_txtBuscarCedulaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String cedula = txtBuscarCedula.getText();

    PersonaDAO dao = new PersonaDAO();

    Persona persona = dao.buscarPorCedula(cedula);

    if (persona != null) {

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Cédula");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Usuario");
    modelo.addColumn("Rol");

    modelo.addRow(new Object[]{
        persona.getCedula(),
        persona.getNombre(),
        persona.getApellido(),
        persona.getUsername(),
        persona.getRol()
    });

    tblUsuarios.setModel(modelo);

    } else {

    JOptionPane.showMessageDialog(
            this,
            "No se encontró el usuario"
    );
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActualizarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedulaActualizar.getText();

    PersonaDAO dao = new PersonaDAO();

    Persona persona = dao.buscarPorCedula(cedula);

    if (persona != null) {

    txtCedulaActualizar.setText(persona.getCedula());
    txtNombreActualizar.setText(persona.getNombre());
    txtApellidoActualizar.setText(persona.getApellido());
    txtTelefonoActualizar.setText(persona.getTelefono());
    txtEmailActualizar.setText(persona.getEmail());
    txtUsernameActualizar.setText(persona.getUsername());
    txtPasswordActualizar.setText(persona.getPassword());

    cmbRolActualizar.setSelectedItem(persona.getRol());

    } else {

    JOptionPane.showMessageDialog(
            this,
            "Usuario no encontrado"
    );
    }
    }//GEN-LAST:event_btnBuscarActualizarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedulaActualizar.getText();
        String nombre = txtNombreActualizar.getText();
        String apellido = txtApellidoActualizar.getText();
        String telefono = txtTelefonoActualizar.getText();
        String email = txtEmailActualizar.getText();
        String username = txtUsernameActualizar.getText();
        String password = txtPasswordActualizar.getText();
        String rol = cmbRolActualizar.getSelectedItem().toString();

        Persona persona = new Persona(
        0,
        cedula,
        nombre,
        apellido,
        telefono,
        email,
        username,
        password,
        rol
        );

        PersonaDAO dao = new PersonaDAO();

        if (dao.actualizarPersona(persona)) {

        JOptionPane.showMessageDialog(
            this,
            "Usuario actualizado correctamente"
        );

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Error al actualizar usuario"
        );
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        // TODO add your handling code here:
        String cedula = txtBuscarCedulaEliminar.getText();

        PersonaDAO dao = new PersonaDAO();

        Persona persona = dao.buscarPorCedula(cedula);

        if (persona != null) {

        txtNombreEliminar.setText(persona.getNombre());
        txtUsuarioEliminar.setText(persona.getUsername());
        cmbRolEliminar.setSelectedItem(persona.getRol());

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Usuario no encontrado"
        );
        }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String cedula = txtBuscarCedulaEliminar.getText();

        PersonaDAO dao = new PersonaDAO();

        int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Desea eliminar este usuario?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

        if (dao.eliminarPersona(cedula)) {

        JOptionPane.showMessageDialog(
                this,
                "Usuario eliminado correctamente"
        );

        } else {

        JOptionPane.showMessageDialog(
                this,
                "Error al eliminar usuario"
        );
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void limpiarCampos() {

    txtCedula.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");
    txtUsername.setText("");
    txtPassword.setText("");

    cmbRol.setSelectedIndex(0);
    }
    
    private void aplicarEstilos() {
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblGestionRegistro);
    EstiloUI.estilizarBotonPrimario(btnGuardar);
    EstiloUI.estilizarBotonPrimario(btnBuscar);
    EstiloUI.estilizarBotonPrimario(btnBuscarActualizar);
    EstiloUI.estilizarBotonPrimario(btnActualizar);
    EstiloUI.estilizarBotonPrimario(btnBuscarEliminar);
    EstiloUI.estilizarBotonPeligro(btnEliminar);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.estilizarBotonSecundario(btnVolver);
    EstiloUI.estilizarCampo(txtCedula);
    EstiloUI.estilizarCampo(txtNombre);
    EstiloUI.estilizarCampo(txtApellido);
    EstiloUI.estilizarCampo(txtEmail);
    EstiloUI.estilizarCampo(txtTelefono);
    EstiloUI.estilizarCampo(txtUsername);
    EstiloUI.estilizarCampo(txtBuscarCedula);
    EstiloUI.estilizarCampo(txtBuscarCedulaEliminar);
    EstiloUI.estilizarCampo(txtNombreEliminar);
    EstiloUI.estilizarCampo(txtUsuarioEliminar);
    EstiloUI.estilizarCampo(txtCedulaActualizar);
    EstiloUI.estilizarCampo(txtNombreActualizar);
    EstiloUI.estilizarCampo(txtApellidoActualizar);
    EstiloUI.estilizarCampo(txtTelefonoActualizar);
    EstiloUI.estilizarCampo(txtEmailActualizar);
    EstiloUI.estilizarCampo(txtUsernameActualizar);
    EstiloUI.estilizarCombo(cmbRol);
    EstiloUI.estilizarCombo(cmbRolActualizar);
    EstiloUI.estilizarCombo(cmbRolEliminar);
    // Estilo botones Ver
    EstiloUI.estilizarBotonSecundario(btnMostrar);
    EstiloUI.estilizarBotonSecundario(btnMostrarC);
    
    // Validaciones de entrada
    EstiloUI.soloNumeros(txtCedula);
    EstiloUI.soloNumeros(txtTelefono);
    EstiloUI.soloNumeros(txtBuscarCedula);
    EstiloUI.soloNumeros(txtBuscarCedulaEliminar);
    EstiloUI.soloNumeros(txtCedulaActualizar);
    EstiloUI.soloLetras(txtNombre);
    EstiloUI.soloLetras(txtApellido);
    EstiloUI.soloLetras(txtNombreActualizar);
    EstiloUI.soloLetras(txtApellidoActualizar);
    EstiloUI.validarEmail(txtEmail);
    EstiloUI.validarEmail(txtEmailActualizar);
    EstiloUI.configurarBtnVolver(btnVolver, this);
    
    }
    
    private void configurarBtnAyuda() {
    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
}
  
    
    private void mostrarAyuda() {

    String[] tabs = {"Registrar", "Consultar", "Eliminar", "Actualizar"};

    String[] descripciones = {
        "<html><b> REGISTRAR USUARIO</b><br><br>"
        + "• <b>Cédula*</b> — Número de identificación del usuario. Obligatorio.<br>"
        + "• <b>Nombre*</b> — Nombre del usuario. Obligatorio.<br>"
        + "• <b>Apellido*</b> — Apellido del usuario. Obligatorio.<br>"
        + "• <b>Teléfono*</b> — Número de contacto. Obligatorio.<br>"
        + "• <b>Email*</b> — Correo electrónico. Obligatorio.<br>"
        + "• <b>Usuario*</b> — Nombre de inicio de sesión. Obligatorio.<br>"
        + "• <b>Contraseña*</b> — Clave de acceso. Obligatorio.<br>"
        + "• <b>Rol*</b> — USUARIO: acceso básico. BIBLIOTECARIO: acceso ampliado.<br><br>"
        + "▶ Presiona <b>Guardar</b> para registrar.</html>",

        "<html><b> CONSULTAR USUARIO</b><br><br>"
        + "• <b>Cédula*</b> — Ingresa la cédula exacta del usuario a buscar.<br><br>"
        + "▶ Presiona <b>Buscar</b> para ver los resultados en la tabla.<br><br>"
        + "• La tabla mostrará: Cédula, Nombre, Apellido, Usuario y Rol.</html>",

        "<html><b> ELIMINAR USUARIO</b><br><br>"
        + "• <b>Cédula*</b> — Ingresa la cédula del usuario a eliminar.<br><br>"
        + "▶ Presiona <b>Buscar</b> para cargar los datos del usuario.<br>"
        + "▶ Verifica Nombre, Usuario y Rol cargados.<br>"
        + "▶ Presiona <b>Eliminar</b> y confirma en el cuadro de diálogo.<br><br>"
        + "⚠ <b>Esta acción no se puede deshacer.</b></html>",

        "<html><b> ACTUALIZAR USUARIO</b><br><br>"
        + "• <b>Cédula*</b> — Ingresa la cédula del usuario a modificar.<br><br>"
        + "▶ Presiona <b>Buscar</b> para cargar los datos actuales.<br>"
        + "▶ Modifica los campos que necesites.<br>"
        + "▶ Presiona <b>Actualizar</b> para guardar los cambios.</html>"
    };

    javax.swing.JTabbedPane tabsAyuda = new javax.swing.JTabbedPane();

    for (int i = 0; i < tabs.length; i++) {
        javax.swing.JLabel lbl = new javax.swing.JLabel(descripciones[i]);
        lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));

        javax.swing.JPanel panel = new javax.swing.JPanel(
            new java.awt.BorderLayout()
        );
        panel.add(lbl, java.awt.BorderLayout.NORTH);
        tabsAyuda.addTab(tabs[i], panel);
    }

    tabsAyuda.setSelectedIndex(jTabbedPane1.getSelectedIndex());

    javax.swing.JOptionPane.showMessageDialog(
        this,
        tabsAyuda,
        "Ayuda — Gestión de Usuarios",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> new GestionUsuarios().setVisible(true));
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarActualizar;
    private javax.swing.JButton btnBuscarEliminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrarC;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbRolActualizar;
    private javax.swing.JComboBox<String> cmbRolEliminar;
    private javax.swing.JLabel jLabel1Cedula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblApellidoActualizar;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulaActualizar;
    private javax.swing.JLabel lblCedulaEliminar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailActualizar;
    private javax.swing.JLabel lblGestionRegistro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreActualizar;
    private javax.swing.JLabel lblNombreEliminar;
    private javax.swing.JLabel lblPasswordActualizar;
    private javax.swing.JLabel lblRolActualizar;
    private javax.swing.JLabel lblRolEliminar;
    private javax.swing.JLabel lblRolRegistrar;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoActualizar;
    private javax.swing.JLabel lblUsernameActualizar;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioEliminar;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoActualizar;
    private javax.swing.JTextField txtBuscarCedula;
    private javax.swing.JTextField txtBuscarCedulaEliminar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaActualizar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailActualizar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombreEliminar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordActualizar;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoActualizar;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsernameActualizar;
    private javax.swing.JTextField txtUsuarioEliminar;
    // End of variables declaration//GEN-END:variables
}
