
package vista;

import controlador.PersonaDAO;
import controlador.LibroDAO;
import java.util.ArrayList;
import java.time.LocalDate;
import controlador.PrestamoDAO;
import modelo.Persona;
import modelo.Libro;
import modelo.Prestamo;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class GestionPrestamos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionPrestamos.class.getName());

    /**
     * Creates new form GestionPrestamos
     */
    public GestionPrestamos() {
    initComponents();

    cargarUsuarios();
    cargarLibros();
    cargarFechas();

    txtFechaPrestamo.setEditable(false);
    txtFechaLimite.setEditable(false);

    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // Estilo y acción btnVolver
    btnVolver.setBackground(new java.awt.Color(100, 100, 100));
    btnVolver.setForeground(java.awt.Color.WHITE);
    btnVolver.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnVolver.setFocusPainted(false);
    btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());
    
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(jLabel1);
    EstiloUI.estilizarBotonPrimario(btnRegistrarPrestamo);
    EstiloUI.estilizarBotonPrimario(btnBuscarIDPrestamos);
    EstiloUI.estilizarBotonPrimario(btnRegistrarDevolucion);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.estilizarCampo(txtFechaPrestamo);
    EstiloUI.estilizarCampo(txtFechaLimite);
    EstiloUI.estilizarCampo(txtIDPrestamo);
    EstiloUI.estilizarCombo(cmbUsuarioPrestamo);
    EstiloUI.estilizarCombo(cmbLibroPrestamo);
    EstiloUI.estilizarCombo(cmbEstadoPrestamo);
    EstiloUI.configurarBtnVolver(btnVolver, this);

    
    EstiloUI.soloNumeros(txtIDPrestamo);

    setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblUsuarioRegistrarPrestamo = new javax.swing.JLabel();
        lblLibroRegistrarPrestamo = new javax.swing.JLabel();
        lblFechaPrestamo = new javax.swing.JLabel();
        lblFechaLimite = new javax.swing.JLabel();
        lblEstadoRegistrarPrestamo = new javax.swing.JLabel();
        cmbUsuarioPrestamo = new javax.swing.JComboBox<>();
        cmbLibroPrestamo = new javax.swing.JComboBox<>();
        txtFechaPrestamo = new javax.swing.JTextField();
        txtFechaLimite = new javax.swing.JTextField();
        cmbEstadoPrestamo = new javax.swing.JComboBox<>();
        btnRegistrarPrestamo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblIDPrestamo = new javax.swing.JLabel();
        txtIDPrestamo = new javax.swing.JTextField();
        btnBuscarIDPrestamos = new javax.swing.JButton();
        lblUsuarioRegistrarDevolucion = new javax.swing.JLabel();
        lblLibroRegistrarDevolucion = new javax.swing.JLabel();
        lblEstadoRegistrarDevolucion = new javax.swing.JLabel();
        txtUsuarioRegistrarDevolucion = new javax.swing.JTextField();
        btnRegistrarDevolucion = new javax.swing.JButton();
        txtLibroRegistrarDevolucion = new javax.swing.JTextField();
        txtEstadoRegistrarDevolucion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuarioRegistrarPrestamo.setText("Usuario* :");

        lblLibroRegistrarPrestamo.setText("Libro* :");

        lblFechaPrestamo.setText("Fecha Préstamo:");

        lblFechaLimite.setText("Fecha Límite:");

        lblEstadoRegistrarPrestamo.setText("Estado:");

        txtFechaPrestamo.setEnabled(false);

        txtFechaLimite.setEnabled(false);

        cmbEstadoPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "DEVUELTO", "EN MORA" }));

        btnRegistrarPrestamo.setText("Registrar Préstamo");
        btnRegistrarPrestamo.addActionListener(this::btnRegistrarPrestamoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuarioRegistrarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLibroRegistrarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstadoRegistrarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUsuarioPrestamo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbLibroPrestamo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaPrestamo)
                            .addComponent(txtFechaLimite)
                            .addComponent(cmbEstadoPrestamo, 0, 120, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioRegistrarPrestamo)
                    .addComponent(cmbUsuarioPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibroRegistrarPrestamo)
                    .addComponent(cmbLibroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPrestamo)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaLimite)
                    .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoRegistrarPrestamo)
                    .addComponent(cmbEstadoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPrestamo)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Préstamo", jPanel2);

        lblIDPrestamo.setText("ID Préstamo: ");

        btnBuscarIDPrestamos.setText("Buscar");
        btnBuscarIDPrestamos.addActionListener(this::btnBuscarIDPrestamosActionPerformed);

        lblUsuarioRegistrarDevolucion.setText("Usuario :");

        lblLibroRegistrarDevolucion.setText("Libro :");

        lblEstadoRegistrarDevolucion.setText("Estado :");

        txtUsuarioRegistrarDevolucion.setEnabled(false);

        btnRegistrarDevolucion.setText("Registrar Devolución");
        btnRegistrarDevolucion.addActionListener(this::btnRegistrarDevolucionActionPerformed);

        txtLibroRegistrarDevolucion.setEnabled(false);

        txtEstadoRegistrarDevolucion.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstadoRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLibroRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuarioRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIDPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDPrestamo)
                            .addComponent(txtUsuarioRegistrarDevolucion)
                            .addComponent(txtLibroRegistrarDevolucion)
                            .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarIDPrestamos))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDPrestamo)
                    .addComponent(txtIDPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIDPrestamos))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioRegistrarDevolucion)
                    .addComponent(txtUsuarioRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibroRegistrarDevolucion)
                    .addComponent(txtLibroRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoRegistrarDevolucion)
                    .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnRegistrarDevolucion)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Registrar Devolución", jPanel3);

        jLabel1.setText("Gestión Préstamos");

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        btnVolver.setText("<-");
        btnVolver.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAyuda)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDevolucionActionPerformed
        // TODO add your handling code here:
        int idPrestamo =
        Integer.parseInt(
            txtIDPrestamo.getText()
        );

        PrestamoDAO prestamoDAO = new PrestamoDAO();
        LibroDAO libroDAO = new LibroDAO();

        Prestamo prestamo =
        prestamoDAO.buscarPrestamoPorId(idPrestamo);

        if (prestamo != null) {

            LocalDate hoy = LocalDate.now();

            LocalDate fechaLimite =
            LocalDate.parse(
                prestamo.getFechaLimite()
            );

            String estado;

            if (hoy.isAfter(fechaLimite)) {

                estado = "EN_MORA";

            } else {

                estado = "DEVUELTO";
            }

            if (prestamoDAO.registrarDevolucion(
                idPrestamo,
                hoy.toString(),
                estado
            )) {

                libroDAO.actualizarEstadoLibro(
                    prestamo.getLibro().getId(),
                    "DISPONIBLE"
                );

                JOptionPane.showMessageDialog(
                    this,
                    "Devolución registrada correctamente"
                );

                txtIDPrestamo.setText("");
                txtUsuarioRegistrarDevolucion.setText("");
                txtLibroRegistrarDevolucion.setText("");
                txtEstadoRegistrarDevolucion.setText("");

            } else {

                JOptionPane.showMessageDialog(
                    this,
                    "Error al registrar devolución"
                );
            }

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Préstamo no encontrado"
            );
        }
    }//GEN-LAST:event_btnRegistrarDevolucionActionPerformed

    private void btnBuscarIDPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDPrestamosActionPerformed
        // TODO add your handling code here:
        int idPrestamo =
        Integer.parseInt(
            txtIDPrestamo.getText()
        );

        PrestamoDAO dao = new PrestamoDAO();

        Prestamo prestamo =
        dao.buscarPrestamoPorId(idPrestamo);

        if (prestamo != null) {

            txtUsuarioRegistrarDevolucion.setText(
                prestamo.getPersona().getNombre()
            );

            txtLibroRegistrarDevolucion.setText(
                prestamo.getLibro().getTitulo()
            );

            txtEstadoRegistrarDevolucion.setText(
                prestamo.getEstado()
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Préstamo no encontrado"
            );
        }
    }//GEN-LAST:event_btnBuscarIDPrestamosActionPerformed

    private void btnRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPrestamoActionPerformed
        // TODO add your handling code here:
        String usuarioSeleccionado =
        cmbUsuarioPrestamo.getSelectedItem().toString();

        String tituloLibro =
        cmbLibroPrestamo.getSelectedItem().toString();

        String cedula =
        usuarioSeleccionado.split(" - ")[0];

        PersonaDAO personaDAO = new PersonaDAO();
        LibroDAO libroDAO = new LibroDAO();
        PrestamoDAO prestamoDAO = new PrestamoDAO();

        Persona persona =
        personaDAO.buscarPorCedula(cedula);

        Libro libro =
        libroDAO.buscarPorTitulo(tituloLibro);

        Prestamo prestamo = new Prestamo(
            0,
            persona,
            libro,
            txtFechaPrestamo.getText(),
            txtFechaLimite.getText(),
            null,
            "PENDIENTE"
        );

        if (prestamoDAO.registrarPrestamo(prestamo)) {

            libroDAO.actualizarEstadoLibro(
                libro.getId(),
                "PRESTADO"
            );

            JOptionPane.showMessageDialog(
                this,
                "Préstamo registrado correctamente"
            );

            cargarLibros();
            cargarFechas();

        } else {

            JOptionPane.showMessageDialog(
                this,
                "Error al registrar préstamo"
            );
        }
    }//GEN-LAST:event_btnRegistrarPrestamoActionPerformed
    
    private void cargarUsuarios() {

    PersonaDAO dao = new PersonaDAO();

    ArrayList<String> usuarios = dao.listarUsuarios();

    cmbUsuarioPrestamo.removeAllItems();

    for (String usuario : usuarios) {

        cmbUsuarioPrestamo.addItem(usuario);
    }
    }
    
    private void cargarLibros() {

    LibroDAO dao = new LibroDAO();

    ArrayList<String> libros = dao.listarLibrosDisponibles();

    cmbLibroPrestamo.removeAllItems();

    for (String libro : libros) {

        cmbLibroPrestamo.addItem(libro);
    }
    }
    private void cargarFechas() {

    LocalDate hoy = LocalDate.now();

    LocalDate fechaLimite = hoy.plusDays(20);

    txtFechaPrestamo.setText(hoy.toString());

    txtFechaLimite.setText(fechaLimite.toString());
    }
    
    private void mostrarAyuda() {

    String[] tabs = {"Registrar Préstamo", "Registrar Devolución"};

    String[] descripciones = {
        "<html><b> REGISTRAR PRÉSTAMO</b><br><br>"
        + "• <b>Usuario*</b> — Selecciona el usuario que solicita el préstamo.<br>"
        + "• <b>Libro*</b> — Selecciona el libro disponible a prestar.<br>"
        + "• <b>Fecha Préstamo</b> — Se asigna automáticamente con la fecha de hoy.<br>"
        + "• <b>Fecha Límite</b> — Se calcula automáticamente (20 días desde hoy).<br>"
        + "• <b>Estado</b> — Se registra como PENDIENTE por defecto.<br><br>"
        + "▶ Presiona <b>Registrar Préstamo</b> para guardar.</html>",

        "<html><b> REGISTRAR DEVOLUCIÓN</b><br><br>"
        + "• <b>ID Préstamo*</b> — Ingresa el número de ID del préstamo a devolver.<br><br>"
        + "▶ Presiona <b>Buscar</b> para cargar los datos del préstamo:<br>"
        + "&nbsp;&nbsp;&nbsp;- Se mostrará el Usuario, Libro y Estado actual.<br><br>"
        + "▶ Verifica los datos y presiona <b>Registrar Devolución</b>.<br><br>"
        + "• Si la devolución es después de la fecha límite, el estado<br>"
        + "&nbsp;&nbsp;&nbsp;quedará como <b>EN_MORA</b>; si es a tiempo, como <b>DEVUELTO</b>.</html>"
    };

    javax.swing.JTabbedPane tabsAyuda = new javax.swing.JTabbedPane();

    for (int i = 0; i < tabs.length; i++) {
        javax.swing.JLabel lbl = new javax.swing.JLabel(descripciones[i]);
        lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));

        javax.swing.JPanel panel = new javax.swing.JPanel(
            new java.awt.BorderLayout()
        );
        panel.add(lbl, java.awt.BorderLayout.NORTH);
        tabsAyuda.addTab(tabs[i], panel);
    }

    tabsAyuda.setSelectedIndex(jTabbedPane1.getSelectedIndex());

    javax.swing.JOptionPane.showMessageDialog(
        this,
        tabsAyuda,
        "Ayuda — Gestión de Préstamos",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionPrestamos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscarIDPrestamos;
    private javax.swing.JButton btnRegistrarDevolucion;
    private javax.swing.JButton btnRegistrarPrestamo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstadoPrestamo;
    private javax.swing.JComboBox<String> cmbLibroPrestamo;
    private javax.swing.JComboBox<String> cmbUsuarioPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEstadoRegistrarDevolucion;
    private javax.swing.JLabel lblEstadoRegistrarPrestamo;
    private javax.swing.JLabel lblFechaLimite;
    private javax.swing.JLabel lblFechaPrestamo;
    private javax.swing.JLabel lblIDPrestamo;
    private javax.swing.JLabel lblLibroRegistrarDevolucion;
    private javax.swing.JLabel lblLibroRegistrarPrestamo;
    private javax.swing.JLabel lblUsuarioRegistrarDevolucion;
    private javax.swing.JLabel lblUsuarioRegistrarPrestamo;
    private javax.swing.JTextField txtEstadoRegistrarDevolucion;
    private javax.swing.JTextField txtFechaLimite;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtIDPrestamo;
    private javax.swing.JTextField txtLibroRegistrarDevolucion;
    private javax.swing.JTextField txtUsuarioRegistrarDevolucion;
    // End of variables declaration//GEN-END:variables
}
