
package vista;

import controlador.LibroDAO;
import modelo.Libro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class GestionLibros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionLibros.class.getName());

    /**
     * Creates new form GestionLibros
     */
    public GestionLibros() {
    initComponents();

    btnAyuda.addActionListener(e -> mostrarAyuda());

    // Hotkey Ctrl+H
    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // Estilo y acción btnAtras
    btnAtras.setBackground(new java.awt.Color(100, 100, 100));
    btnAtras.setForeground(java.awt.Color.WHITE);
    btnAtras.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnAtras.setFocusPainted(false);
    btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAtras.setText("←");
    btnAtras.addActionListener(e -> dispose());
    
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblGestionLibros);
    EstiloUI.estilizarBotonPrimario(btnGuardarLibro);
    EstiloUI.estilizarBotonPrimario(btnBuscarLibro);
    EstiloUI.estilizarBotonPrimario(btnBuscarLibroActualizar);
    EstiloUI.estilizarBotonPrimario(btnActualizarLibro);
    EstiloUI.estilizarBotonPrimario(btnBuscarLibroEliminar);
    EstiloUI.estilizarBotonPeligro(btnEliminarLibro);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.estilizarBotonSecundario(btnAtras);
    // Campos
    EstiloUI.estilizarCampo(txtTitulo);
    EstiloUI.estilizarCampo(txtAutor);
    EstiloUI.estilizarCampo(txtAnioPublicacion);
    EstiloUI.estilizarCampo(txtBuscarTitulo);
    EstiloUI.estilizarCampo(txtBuscarTituloEliminar);
    EstiloUI.estilizarCampo(txtBuscarTituloActualizar);
    EstiloUI.estilizarCombo(cmbEstado);
    EstiloUI.estilizarCombo(cmbEstadoActualizar);
    EstiloUI.estilizarCombo(cmbEstadoEliminar);

    // Validaciones — solo números
    EstiloUI.soloNumeros(txtAnioPublicacion);
    EstiloUI.soloNumeros(txtAnioPublicacionActualizar);

    // Validaciones — solo letras (títulos y autores)
    EstiloUI.soloLetras(txtTitulo);
    EstiloUI.soloLetras(txtAutor);
    EstiloUI.soloLetras(txtBuscarTitulo);
    EstiloUI.soloLetras(txtTituloActualizar);
    EstiloUI.soloLetras(txtAutorActualizar);
    EstiloUI.soloLetras(txtBuscarTituloEliminar);
    EstiloUI.soloLetras(txtBuscarTituloActualizar);
    EstiloUI.configurarBtnVolver(btnAtras, this);
    
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGestionLibros = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblAnioPublicacion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnGuardarLibro = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAnioPublicacion = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblTituloConsultar = new javax.swing.JLabel();
        txtBuscarTitulo = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblBuscarTituloEliminar = new javax.swing.JLabel();
        txtTituloEliminar = new javax.swing.JTextField();
        btnBuscarLibroEliminar = new javax.swing.JButton();
        lblTituloEliminar = new javax.swing.JLabel();
        txtBuscarTituloEliminar = new javax.swing.JTextField();
        lblAutorEliminar = new javax.swing.JLabel();
        lblAnioPublicacionEliminar = new javax.swing.JLabel();
        lblEstadoEliminar = new javax.swing.JLabel();
        txtAutorEliminar = new javax.swing.JTextField();
        txtAnioPublicacionEliminar = new javax.swing.JTextField();
        cmbEstadoEliminar = new javax.swing.JComboBox<>();
        btnEliminarLibro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblBuscarTituloActualizar = new javax.swing.JLabel();
        txtTituloActualizar = new javax.swing.JTextField();
        btnBuscarLibroActualizar = new javax.swing.JButton();
        lblTituloActualizar = new javax.swing.JLabel();
        txtBuscarTituloActualizar = new javax.swing.JTextField();
        lblAutorActualizar = new javax.swing.JLabel();
        lblAnioPublicacionActualizar = new javax.swing.JLabel();
        lblEstadoActualizar = new javax.swing.JLabel();
        txtAutorActualizar = new javax.swing.JTextField();
        txtAnioPublicacionActualizar = new javax.swing.JTextField();
        cmbEstadoActualizar = new javax.swing.JComboBox<>();
        btnActualizarLibro = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGestionLibros.setText("Gestión Libros");

        lblTitulo.setText("Título* :");

        lblAutor.setText("Autor* :");

        lblAnioPublicacion.setText("Año Publicación:");

        lblEstado.setText("Estado :");

        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.addActionListener(this::btnGuardarLibroActionPerformed);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "PRESTADO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAnioPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitulo)
                            .addComponent(txtAutor)
                            .addComponent(txtAnioPublicacion)
                            .addComponent(cmbEstado, 0, 151, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioPublicacion)
                    .addComponent(txtAnioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnGuardarLibro)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar", jPanel1);

        lblTituloConsultar.setText("Título* :");

        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(this::btnBuscarLibroActionPerformed);

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Año Publicación", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTituloConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarLibro)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloConsultar)
                    .addComponent(txtBuscarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel3);

        lblBuscarTituloEliminar.setText("Título* :");

        txtTituloEliminar.setEnabled(false);

        btnBuscarLibroEliminar.setText("Buscar");
        btnBuscarLibroEliminar.addActionListener(this::btnBuscarLibroEliminarActionPerformed);

        lblTituloEliminar.setText("Título :");

        lblAutorEliminar.setText("Autor:");

        lblAnioPublicacionEliminar.setText("Año Publicación:");

        lblEstadoEliminar.setText("Estado :");

        txtAutorEliminar.setEnabled(false);

        txtAnioPublicacionEliminar.setEnabled(false);

        cmbEstadoEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "PRESTADO" }));
        cmbEstadoEliminar.setEnabled(false);

        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(this::btnEliminarLibroActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(lblAutorEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtBuscarTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscarLibroEliminar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAutorEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtTituloEliminar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblAnioPublicacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnioPublicacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblEstadoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstadoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarTituloEliminar)
                    .addComponent(btnBuscarLibroEliminar)
                    .addComponent(txtBuscarTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloEliminar)
                    .addComponent(txtTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnioPublicacionEliminar)
                    .addComponent(txtAnioPublicacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorEliminar)
                    .addComponent(txtAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoEliminar)
                    .addComponent(cmbEstadoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnEliminarLibro)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Eliminar", jPanel5);

        lblBuscarTituloActualizar.setText("Título* :");

        btnBuscarLibroActualizar.setText("Buscar");
        btnBuscarLibroActualizar.addActionListener(this::btnBuscarLibroActualizarActionPerformed);

        lblTituloActualizar.setText("Título :");

        lblAutorActualizar.setText("Autor:");

        lblAnioPublicacionActualizar.setText("Año Publicación:");

        lblEstadoActualizar.setText("Estado :");

        cmbEstadoActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "PRESTADO" }));

        btnActualizarLibro.setText("Actualizar");
        btnActualizarLibro.addActionListener(this::btnActualizarLibroActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAutorActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtBuscarTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscarLibroActualizar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAutorActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtTituloActualizar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblAnioPublicacionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAnioPublicacionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblEstadoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstadoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnActualizarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarTituloActualizar)
                    .addComponent(btnBuscarLibroActualizar)
                    .addComponent(txtBuscarTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloActualizar)
                    .addComponent(txtTituloActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnioPublicacionActualizar)
                    .addComponent(txtAnioPublicacionActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorActualizar)
                    .addComponent(txtAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoActualizar)
                    .addComponent(cmbEstadoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnActualizarLibro)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Actualizar", jPanel4);

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        btnAtras.setText("<-");
        btnAtras.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblGestionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionLibros)
                    .addComponent(btnAyuda)
                    .addComponent(btnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // TODO add your handling code here:
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();

        int anioPublicacion = Integer.parseInt(
        txtAnioPublicacion.getText()
        );

        String estado = cmbEstado.getSelectedItem().toString();

        Libro libro = new Libro(
        0,
        titulo,
        autor,
        anioPublicacion,
        estado
        );

        LibroDAO dao = new LibroDAO();

        if (dao.guardarLibro(libro)) {

        JOptionPane.showMessageDialog(
            this,
            "Libro registrado correctamente"
        );
        } else {

        JOptionPane.showMessageDialog(
            this,
            "Error al registrar libro"
        );
        }
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
        // TODO add your handling code here:
        String titulo = txtBuscarTitulo.getText();

        LibroDAO dao = new LibroDAO();

        Libro libro = dao.buscarPorTitulo(titulo);

        if (libro != null) {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Título");
        modelo.addColumn("Autor");
        modelo.addColumn("Año");
        modelo.addColumn("Estado");

        modelo.addRow(new Object[]{
        libro.getTitulo(),
        libro.getAutor(),
        libro.getAnioPublicacion(),
        libro.getEstado()
        });

        tblLibros.setModel(modelo);

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Libro no encontrado"
        );
        }
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnBuscarLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActualizarActionPerformed
        // TODO add your handling code here:
        String titulo = txtBuscarTituloActualizar.getText();

        LibroDAO dao = new LibroDAO();

        Libro libro = dao.buscarPorTitulo(titulo);

        if (libro != null) {

        txtTituloActualizar.setText(libro.getTitulo());
        txtAutorActualizar.setText(libro.getAutor());
        txtAnioPublicacionActualizar.setText(
            String.valueOf(libro.getAnioPublicacion())
        );

        cmbEstadoActualizar.setSelectedItem(
            libro.getEstado()
        );

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Libro no encontrado"
        );
        }
    }//GEN-LAST:event_btnBuscarLibroActualizarActionPerformed

    private void btnActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroActionPerformed
        // TODO add your handling code here:
        String titulo = txtTituloActualizar.getText();
        String autor = txtAutorActualizar.getText();

        int anioPublicacion = Integer.parseInt(
        txtAnioPublicacionActualizar.getText()
        );

        String estado = cmbEstadoActualizar
        .getSelectedItem()
        .toString();

        Libro libro = new Libro(
        0,
        titulo,
        autor,
        anioPublicacion,
        estado
        );

        LibroDAO dao = new LibroDAO();

        if (dao.actualizarLibro(libro)) {

        JOptionPane.showMessageDialog(
            this,
            "Libro actualizado correctamente"
        );

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Error al actualizar libro"
        );
        }
    }//GEN-LAST:event_btnActualizarLibroActionPerformed

    private void btnBuscarLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroEliminarActionPerformed
        // TODO add your handling code here:
        String titulo = txtBuscarTituloEliminar.getText();

        LibroDAO dao = new LibroDAO();

        Libro libro = dao.buscarPorTitulo(titulo);

        if (libro != null) {

        txtTituloEliminar.setText(libro.getTitulo());
        txtAutorEliminar.setText(libro.getAutor());

        txtAnioPublicacionEliminar.setText(
            String.valueOf(libro.getAnioPublicacion())
        );

        cmbEstadoEliminar.setSelectedItem(
            libro.getEstado()
        );

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Libro no encontrado"
        );
        }
    }//GEN-LAST:event_btnBuscarLibroEliminarActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
        String titulo = txtBuscarTituloEliminar.getText();

        LibroDAO dao = new LibroDAO();

        int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Desea eliminar este libro?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

        if (dao.eliminarLibro(titulo)) {

        JOptionPane.showMessageDialog(
                this,
                "Libro eliminado correctamente"
        );

        } else {

        JOptionPane.showMessageDialog(
                this,
                "Error al eliminar libro"
        );
        }
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed
    private void limpiarCamposLibro() {

    txtTitulo.setText("");
    txtAutor.setText("");
    txtAnioPublicacion.setText("");

    cmbEstado.setSelectedIndex(0);
    }
    
    private void mostrarAyuda() {

    String[] tabs = {"Registrar", "Consultar", "Eliminar", "Actualizar"};

    String[] descripciones = {
        "<html><b> REGISTRAR LIBRO</b><br><br>"
        + "• <b>Título*</b> — Nombre del libro. Campo obligatorio.<br>"
        + "• <b>Autor*</b> — Nombre del autor. Campo obligatorio.<br>"
        + "• <b>Año Publicación</b> — Año en que fue publicado (ej: 2020).<br>"
        + "• <b>Estado</b> — DISPONIBLE: el libro está en stock.<br>"
        + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
        + "PRESTADO: el libro ya fue prestado.<br><br>"
        + "▶ Presiona <b>Guardar</b> para registrar el libro.</html>",

        "<html><b> CONSULTAR LIBRO</b><br><br>"
        + "• <b>Título*</b> — Escribe el título exacto o parcial del libro.<br><br>"
        + "▶ Presiona <b>Buscar</b> para ver los resultados en la tabla.<br><br>"
        + "• La tabla mostrará: Título, Autor, Año de Publicación y Estado.</html>",

        "<html><b> ELIMINAR LIBRO</b><br><br>"
        + "• <b>Título*</b> — Escribe el título del libro a eliminar.<br><br>"
        + "▶ Presiona <b>Buscar</b> para cargar los datos del libro.<br>"
        + "▶ Verifica los datos cargados (Título, Autor, Año, Estado).<br>"
        + "▶ Presiona <b>Eliminar</b> y confirma en el cuadro de diálogo.<br><br>"
        + "⚠ <b>Esta acción no se puede deshacer.</b></html>",

        "<html><b> ACTUALIZAR LIBRO</b><br><br>"
        + "• <b>Título*</b> — Escribe el título del libro a modificar.<br><br>"
        + "▶ Presiona <b>Buscar</b> para cargar los datos actuales.<br>"
        + "▶ Modifica los campos que necesites:<br>"
        + "&nbsp;&nbsp;&nbsp;- Título, Autor, Año de Publicación, Estado.<br>"
        + "▶ Presiona <b>Actualizar</b> para guardar los cambios.</html>"
    };

    // Panel con pestañas de ayuda
    javax.swing.JTabbedPane tabsAyuda = new javax.swing.JTabbedPane();

    for (int i = 0; i < tabs.length; i++) {
        javax.swing.JLabel lbl = new javax.swing.JLabel(descripciones[i]);
        lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));

        javax.swing.JPanel panel = new javax.swing.JPanel(
            new java.awt.BorderLayout()
        );
        panel.add(lbl, java.awt.BorderLayout.NORTH);
        tabsAyuda.addTab(tabs[i], panel);
    }

    // Sincronizar con la pestaña activa
    tabsAyuda.setSelectedIndex(jTabbedPane1.getSelectedIndex());

    javax.swing.JOptionPane.showMessageDialog(
        this,
        tabsAyuda,
        "Ayuda — Gestión de Libros",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionLibros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLibro;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscarLibro;
    private javax.swing.JButton btnBuscarLibroActualizar;
    private javax.swing.JButton btnBuscarLibroEliminar;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbEstadoActualizar;
    private javax.swing.JComboBox<String> cmbEstadoEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAnioPublicacion;
    private javax.swing.JLabel lblAnioPublicacionActualizar;
    private javax.swing.JLabel lblAnioPublicacionEliminar;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAutorActualizar;
    private javax.swing.JLabel lblAutorEliminar;
    private javax.swing.JLabel lblBuscarTituloActualizar;
    private javax.swing.JLabel lblBuscarTituloEliminar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoActualizar;
    private javax.swing.JLabel lblEstadoEliminar;
    private javax.swing.JLabel lblGestionLibros;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloActualizar;
    private javax.swing.JLabel lblTituloConsultar;
    private javax.swing.JLabel lblTituloEliminar;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAnioPublicacion;
    private javax.swing.JTextField txtAnioPublicacionActualizar;
    private javax.swing.JTextField txtAnioPublicacionEliminar;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutorActualizar;
    private javax.swing.JTextField txtAutorEliminar;
    private javax.swing.JTextField txtBuscarTitulo;
    private javax.swing.JTextField txtBuscarTituloActualizar;
    private javax.swing.JTextField txtBuscarTituloEliminar;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloActualizar;
    private javax.swing.JTextField txtTituloEliminar;
    // End of variables declaration//GEN-END:variables
}
