
package vista;

import controlador.InformeDAO;
/**
 *
 * @author User
 */
public class Informes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Informes.class.getName());

    /**
     * Creates new form Informes
     */
    public Informes() {
    initComponents();

    // Estilo botón ayuda
    btnAyuda.setBackground(new java.awt.Color(70, 130, 180));
    btnAyuda.setForeground(java.awt.Color.WHITE);
    btnAyuda.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
    btnAyuda.setFocusPainted(false);
    btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // Estilo y acción btnVolver
    btnVolver.setBackground(new java.awt.Color(100, 100, 100));
    btnVolver.setForeground(java.awt.Color.WHITE);
    btnVolver.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnVolver.setFocusPainted(false);
    btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());
    
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblInformes);
    EstiloUI.estilizarLabel(lblTotalPrestamos);
    EstiloUI.estilizarLabel(lblLibrosDevueltos);
    EstiloUI.estilizarLabel(lblLibrosEnMora);
    EstiloUI.estilizarCampo(txtTotalPrestamos);
    EstiloUI.estilizarCampo(txtLibrosDevueltos);
    EstiloUI.estilizarCampo(txtLibrosEnMora);
    EstiloUI.estilizarBotonPrimario(btnGenerarInformes);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.estilizarBotonSecundario(btnVolver);
    EstiloUI.configurarBtnVolver(btnVolver, this);

    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformes = new javax.swing.JLabel();
        lblTotalPrestamos = new javax.swing.JLabel();
        lblLibrosDevueltos = new javax.swing.JLabel();
        lblLibrosEnMora = new javax.swing.JLabel();
        btnGenerarInformes = new javax.swing.JButton();
        txtTotalPrestamos = new javax.swing.JTextField();
        txtLibrosDevueltos = new javax.swing.JTextField();
        txtLibrosEnMora = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInformes.setText("INFORMES ");

        lblTotalPrestamos.setText("Total de Préstamos :");

        lblLibrosDevueltos.setText("Libros Devueltos :");

        lblLibrosEnMora.setText("Libros En Mora :");

        btnGenerarInformes.setText("Generar Informes");
        btnGenerarInformes.addActionListener(this::btnGenerarInformesActionPerformed);

        txtTotalPrestamos.setEnabled(false);

        txtLibrosDevueltos.setEnabled(false);

        txtLibrosEnMora.setEnabled(false);

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        btnVolver.setText("<-");
        btnVolver.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLibrosDevueltos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLibrosEnMora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibrosDevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibrosEnMora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInformes)
                    .addComponent(btnAyuda)
                    .addComponent(btnVolver))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPrestamos)
                    .addComponent(txtTotalPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibrosDevueltos)
                    .addComponent(txtLibrosDevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibrosEnMora)
                    .addComponent(txtLibrosEnMora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnGenerarInformes)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarInformesActionPerformed
        // TODO add your handling code here:
        InformeDAO dao = new InformeDAO();

        txtTotalPrestamos.setText(
        String.valueOf(
                dao.totalPrestamos()
        )
        );

        txtLibrosDevueltos.setText(
        String.valueOf(
                dao.totalDevueltos()
        )
        );

        txtLibrosEnMora.setText(
        String.valueOf(
                dao.totalEnMora()
        )
        );
    }//GEN-LAST:event_btnGenerarInformesActionPerformed

    private void mostrarAyuda() {

    String contenido =
        "<html><body style='font-family:SansSerif; padding:8px'>"
        + "<h3 style='color:#2c6fad'> INFORMES DE LA BIBLIOTECA</h3>"
        + "<hr>"
        + "<p>Esta pantalla muestra estadísticas generales del sistema.</p>"
        + "<br>"
        + "<p><b>Total de Préstamos</b> — Número total de préstamos "
        + "registrados en el sistema.</p>"
        + "<p><b>Libros Devueltos</b> — Cantidad de préstamos cuyo "
        + "estado es DEVUELTO.</p>"
        + "<p><b>Libros En Mora</b> — Cantidad de préstamos cuyo "
        + "estado es EN_MORA (devueltos tarde o no devueltos).</p>"
        + "<br>"
        + "<p>▶ Presiona <b>Generar Informes</b> para cargar y "
        + "actualizar los datos en pantalla.</p>"
        + "</body></html>";

    javax.swing.JLabel lbl = new javax.swing.JLabel(contenido);
    lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        lbl,
        "Ayuda — Informes",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Informes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnGenerarInformes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblInformes;
    private javax.swing.JLabel lblLibrosDevueltos;
    private javax.swing.JLabel lblLibrosEnMora;
    private javax.swing.JLabel lblTotalPrestamos;
    private javax.swing.JTextField txtLibrosDevueltos;
    private javax.swing.JTextField txtLibrosEnMora;
    private javax.swing.JTextField txtTotalPrestamos;
    // End of variables declaration//GEN-END:variables
}
