
package vista;

import controlador.PersonaDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Persona;
/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
    initComponents();

    // Estilo botón ayuda
    btnAyuda.setBackground(new java.awt.Color(70, 130, 180));
    btnAyuda.setForeground(java.awt.Color.WHITE);
    btnAyuda.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
    btnAyuda.setFocusPainted(false);
    btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // ── Estilos ──────────────────────────────────
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblLogin);
    EstiloUI.estilizarLabel(lblUsuario);
    EstiloUI.estilizarLabel(lblPassword);
    EstiloUI.estilizarCampo(txtUsuario);
    EstiloUI.estilizarCampo(txtPassword);
    EstiloUI.estilizarBotonPrimario(btnIniciarSesion);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    
  
JButton btnVerPassword = new JButton("👁");
btnVerPassword.setFont(new Font("SansSerif", Font.PLAIN, 12));
btnVerPassword.setPreferredSize(new Dimension(34, 26));
btnVerPassword.setFocusPainted(false);
btnVerPassword.setBackground(new Color(52, 120, 200));
btnVerPassword.setForeground(Color.WHITE);
btnVerPassword.setBorderPainted(false);
btnVerPassword.setCursor(new Cursor(Cursor.HAND_CURSOR));

final boolean[] verPass = {false};
btnVerPassword.addActionListener(e -> {
    verPass[0] = !verPass[0];
    txtPassword.setEchoChar(verPass[0] ? (char)0 : '•');
    btnVerPassword.setText(verPass[0] ? "🙈" : "👁");
});

// Agregar el botón al lado del campo de contraseña

getContentPane().add(btnVerPassword);
// Posicionar manualmente (ajusta x,y según tu ventana):
btnVerPassword.setBounds(
    txtPassword.getX() + txtPassword.getWidth() + 2,
    txtPassword.getY(),
    34, 26
);

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Biblioteca");

        lblUsuario.setText("Usuario* :");

        lblPassword.setText("Contraseña* :");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        txtPassword.setText("jPasswordField1");

        lblLogin.setText("Login");

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAyuda)
                    .addComponent(lblLogin))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnIniciarSesion)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String password = String.valueOf(txtPassword.getPassword());

        PersonaDAO dao = new PersonaDAO();

        Persona persona = dao.iniciarSesion(usuario, password);

        if (persona != null) {

        JOptionPane.showMessageDialog(
            this,
            "Bienvenido " + persona.getNombre()
        );

        if (persona.getRol().equals("ADMINISTRADOR")) {

        MenuAdministrador menu = new MenuAdministrador();
        menu.setVisible(true);
        this.dispose();

        } else if (persona.getRol().equals("BIBLIOTECARIO")) {

        MenuBibliotecario menu = new MenuBibliotecario();
        menu.setVisible(true);
        this.dispose();

        } else if (persona.getRol().equals("USUARIO")) {

        MenuUsuario menu = new MenuUsuario(persona);
        menu.setVisible(true);
        this.dispose();
        }

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Usuario o contraseña incorrectos"
        );
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void mostrarAyuda() {

    String contenido =
        "<html><body style='font-family:SansSerif; padding:8px'>"
        + "<h3 style='color:#2c6fad'> INICIO DE SESIÓN</h3>"
        + "<hr>"
        + "<p><b>Usuario*</b> — Ingresa tu nombre de usuario registrado "
        + "en el sistema.</p>"
        + "<p><b>Contraseña*</b> — Ingresa tu contraseña de acceso.</p>"
        + "<br>"
        + "<p>▶ Presiona <b>Iniciar Sesión</b> para entrar al sistema.</p>"
        + "<br>"
        + "<p>Según tu rol, el sistema te redirigirá a:</p>"
        + "<ul>"
        + "<li> <b>ADMINISTRADOR</b> — Menú de administración completa.</li>"
        + "<li> <b>BIBLIOTECARIO</b> — Menú de gestión de biblioteca.</li>"
        + "<li> <b>USUARIO</b> — Menú de consultas y préstamos.</li>"
        + "</ul>"
        + "<br>"
        + "<p style='color:gray'>💡 Si no recuerdas tu contraseña, "
        + "contacta al administrador del sistema.</p>"
        + "</body></html>";

    javax.swing.JLabel lbl = new javax.swing.JLabel(contenido);
    lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        lbl,
        "Ayuda — Login",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
