
package vista;

import modelo.Persona;
import java.time.LocalDate;
/**
 *
 * @author User
 */
public class MenuUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUsuario.class.getName());
    private Persona usuario;
    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
    initComponents();
    configurarBtnAyuda();
    
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblMenuUsuario);
    EstiloUI.estilizarBotonPrimario(btnConsultarLibros);
    EstiloUI.estilizarBotonPrimario(btnSolicitarPrestamo);
    EstiloUI.estilizarBotonPrimario(btnDevolverLibro);
    EstiloUI.estilizarBotonSecundario(btnCerrarSesion);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    
    setLocationRelativeTo(null);
    }

    public MenuUsuario(Persona usuario) {
    initComponents();
    this.usuario = usuario;
    setTitle("Menú Usuario - " + usuario.getNombre() + " " + usuario.getApellido());
    configurarBtnAyuda();
    setLocationRelativeTo(null);
    }
    
    public Persona getUsuario() {
    return usuario;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuUsuario = new javax.swing.JLabel();
        btnConsultarLibros = new javax.swing.JButton();
        btnSolicitarPrestamo = new javax.swing.JButton();
        btnDevolverLibro = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenuUsuario.setText("Menú Usuario");

        btnConsultarLibros.setText("Consultar Disponibilidad de Libros");
        btnConsultarLibros.addActionListener(this::btnConsultarLibrosActionPerformed);

        btnSolicitarPrestamo.setText("Solicitar Préstamo de un Libro");
        btnSolicitarPrestamo.addActionListener(this::btnSolicitarPrestamoActionPerformed);

        btnDevolverLibro.setText("Devolver Libro");
        btnDevolverLibro.addActionListener(this::btnDevolverLibroActionPerformed);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSolicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMenuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenuUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarLibros)
                .addGap(18, 18, 18)
                .addComponent(btnSolicitarPrestamo)
                .addGap(18, 18, 18)
                .addComponent(btnDevolverLibro)
                .addGap(35, 35, 35)
                .addComponent(btnCerrarSesion)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarPrestamoActionPerformed
        // TODO add your handling code here:
        if (usuario == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
        "No hay usuario autenticado.", "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
        }
        SolicitarPrestamoUsuario ventana = new SolicitarPrestamoUsuario(usuario);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnSolicitarPrestamoActionPerformed

    private void btnConsultarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLibrosActionPerformed
        // TODO add your handling code here:
        ConsultarLibrosUsuario ventana = new ConsultarLibrosUsuario();
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultarLibrosActionPerformed

    private void btnDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibroActionPerformed
        // TODO add your handling code here:
        DevolverLibro ventana = new DevolverLibro();
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnDevolverLibroActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Deseas cerrar sesión?",
        "Cerrar Sesión",
        javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        new Login().setVisible(true); 
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void configurarBtnAyuda() {
    btnAyuda.setBackground(new java.awt.Color(70, 130, 180));
    btnAyuda.setForeground(java.awt.Color.WHITE);
    btnAyuda.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
    btnAyuda.setFocusPainted(false);
    btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
}

private void mostrarAyuda() {
    String contenido =
        "<html><body style='font-family:SansSerif; padding:8px'>"
        + "<h3 style='color:#2c6fad'> MENÚ USUARIO</h3>"
        + "<hr>"
        + "<p>Como usuario tienes acceso a las siguientes opciones:</p>"
        + "<ul>"
        + "<li><b>Consultar Disponibilidad de Libros</b> — Ver qué libros "
        + "están disponibles para préstamo en este momento.</li>"
        + "<li><b>Solicitar Préstamo de un Libro</b> — Selecciona un libro "
        + "disponible y solicita su préstamo. Tienes 20 días para devolverlo.</li>"
        + "<li><b>Devolver Libro</b> — Registra la devolución de un libro "
        + "usando el ID de tu préstamo.</li>"
        + "<li><b>Cerrar Sesión</b> — Sale del sistema y regresa al Login.</li>"
        + "</ul>"
        + "<br>"
        + "<p style='color:#c0392b'>⚠ Devuelve los libros antes de la "
        + "fecha límite para evitar mora.</p>"
        + "<br>"
        + "<p style='color:gray'>💡 Atajo de teclado: <b>Ctrl+H</b> "
        + "para abrir esta ayuda en cualquier momento.</p>"
        + "</body></html>";

    javax.swing.JLabel lbl = new javax.swing.JLabel(contenido);
    lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

    javax.swing.JOptionPane.showMessageDialog(
        this, lbl,
        "Ayuda — Menú Usuario",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarLibros;
    private javax.swing.JButton btnDevolverLibro;
    private javax.swing.JButton btnSolicitarPrestamo;
    private javax.swing.JLabel lblMenuUsuario;
    // End of variables declaration//GEN-END:variables
}



       

