
package vista;

import java.time.LocalDate;
import modelo.Persona;
import controlador.LibroDAO;
import java.util.ArrayList;
import controlador.PrestamoDAO;
import modelo.Libro;
import modelo.Prestamo;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class SolicitarPrestamoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SolicitarPrestamoUsuario.class.getName());

    private Persona usuario;
    /**
     * Creates new form SolicitarPrestamoUsuario
     */
    public SolicitarPrestamoUsuario(Persona usuario) {
    initComponents();

    this.usuario = usuario;

    txtUsuarioSolicitarPrestamos.setText(
        usuario.getNombre() + " " + usuario.getApellido()
    );
    txtUsuarioSolicitarPrestamos.setEditable(false);

    LocalDate hoy = LocalDate.now();
    txtFechaSolicitarPrestamos.setText(hoy.toString());
    txtFechaSolicitarPrestamos.setEditable(false);

    txtFechaLimiteSolicitarPrestamo.setText(hoy.plusDays(20).toString());
    txtFechaLimiteSolicitarPrestamo.setEditable(false);

    cargarLibros();

    // Estilos — igual que las demás ventanas
    EstiloUI.aplicarFondoVentana(this);
    EstiloUI.estilizarTitulo(lblSolicitarPrestamoUsuario);
    EstiloUI.estilizarBotonPrimario(btnSolicitarPrestamo);
    EstiloUI.estilizarBotonAyuda(btnAyuda);
    EstiloUI.estilizarBotonSecundario(btnVolver);
    EstiloUI.estilizarCampo(txtUsuarioSolicitarPrestamos);
    EstiloUI.estilizarCampo(txtFechaSolicitarPrestamos);
    EstiloUI.estilizarCampo(txtFechaLimiteSolicitarPrestamo);
    EstiloUI.estilizarCombo(cmbLibroSolicitarPrestamo);
    EstiloUI.estilizarLabel(lblUsuarioSolicitarPrestamo);
    EstiloUI.estilizarLabel(lblLibroSolicitarPrestamo);
    EstiloUI.estilizarLabel(lblFechaSolicitarPrestamo);
    EstiloUI.estilizarLabel(lblFechaLimiteSolicitar);
    EstiloUI.configurarBtnVolver(btnVolver, this);

    // Botón volver
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());

    // Ayuda
    btnAyuda.addActionListener(e -> mostrarAyuda());

    // Ctrl+H
    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );

    setLocationRelativeTo(null);
}

public SolicitarPrestamoUsuario() {
    initComponents();
    configurarBtnAyuda(); // ← también aquí
    setLocationRelativeTo(null);
}

private void configurarBtnAyuda() {
    btnAyuda.setBackground(new java.awt.Color(70, 130, 180));
    btnAyuda.setForeground(java.awt.Color.WHITE);
    btnAyuda.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
    btnAyuda.setFocusPainted(false);
    btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAyuda.addActionListener(e -> mostrarAyuda());

    javax.swing.KeyStroke ctrlH = javax.swing.KeyStroke.getKeyStroke(
        java.awt.event.KeyEvent.VK_H,
        java.awt.event.InputEvent.CTRL_DOWN_MASK
    );
    getRootPane().getInputMap(
        javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
    ).put(ctrlH, "abrirAyuda");
    getRootPane().getActionMap().put("abrirAyuda",
        new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mostrarAyuda();
            }
        }
    );
    
    // Estilo y acción btnVolver
    btnVolver.setBackground(new java.awt.Color(100, 100, 100));
    btnVolver.setForeground(java.awt.Color.WHITE);
    btnVolver.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
    btnVolver.setFocusPainted(false);
    btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnVolver.setText("←");
    btnVolver.addActionListener(e -> dispose());
    }
    
    private void cargarLibros() {

    LibroDAO dao = new LibroDAO();

    ArrayList<String> libros =
            dao.listarLibrosDisponibles();

    cmbLibroSolicitarPrestamo.removeAllItems();

    for (String libro : libros) {

        cmbLibroSolicitarPrestamo.addItem(libro);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioSolicitarPrestamo = new javax.swing.JLabel();
        txtUsuarioSolicitarPrestamos = new javax.swing.JTextField();
        lblLibroSolicitarPrestamo = new javax.swing.JLabel();
        cmbLibroSolicitarPrestamo = new javax.swing.JComboBox<>();
        lblFechaSolicitarPrestamo = new javax.swing.JLabel();
        txtFechaSolicitarPrestamos = new javax.swing.JTextField();
        lblFechaLimiteSolicitar = new javax.swing.JLabel();
        txtFechaLimiteSolicitarPrestamo = new javax.swing.JTextField();
        btnSolicitarPrestamo = new javax.swing.JButton();
        lblSolicitarPrestamoUsuario = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuarioSolicitarPrestamo.setText("Usuario:");

        lblLibroSolicitarPrestamo.setText("Libro :");

        lblFechaSolicitarPrestamo.setText("Fecha Préstamo :");

        txtFechaSolicitarPrestamos.setEnabled(false);

        lblFechaLimiteSolicitar.setText("Fecha Límite :");

        txtFechaLimiteSolicitarPrestamo.setEnabled(false);

        btnSolicitarPrestamo.setText("Solicitar Préstamo");
        btnSolicitarPrestamo.addActionListener(this::btnSolicitarPrestamoActionPerformed);

        lblSolicitarPrestamoUsuario.setText("Solicitar Préstamo");

        btnAyuda.setText("?");
        btnAyuda.setToolTipText("Ayuda\nCtrl + H");

        btnVolver.setText("<-");
        btnVolver.setToolTipText("Atrás\nCtrl + R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSolicitarPrestamoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFechaLimiteSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaSolicitarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLibroSolicitarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuarioSolicitarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuarioSolicitarPrestamos)
                                .addComponent(cmbLibroSolicitarPrestamo, 0, 105, Short.MAX_VALUE)
                                .addComponent(txtFechaSolicitarPrestamos)
                                .addComponent(txtFechaLimiteSolicitarPrestamo))
                            .addComponent(btnSolicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitarPrestamoUsuario)
                    .addComponent(btnAyuda)
                    .addComponent(btnVolver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioSolicitarPrestamo)
                    .addComponent(txtUsuarioSolicitarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibroSolicitarPrestamo)
                    .addComponent(cmbLibroSolicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSolicitarPrestamo)
                    .addComponent(txtFechaSolicitarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaLimiteSolicitar)
                    .addComponent(txtFechaLimiteSolicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSolicitarPrestamo)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarPrestamoActionPerformed
        // TODO add your handling code here:
        LibroDAO libroDAO = new LibroDAO();
        PrestamoDAO prestamoDAO = new PrestamoDAO();

        String tituloLibro =
        cmbLibroSolicitarPrestamo
        .getSelectedItem()
        .toString();

        Libro libro =
        libroDAO.buscarPorTitulo(
                tituloLibro
        );

        Prestamo prestamo = new Prestamo(

        0,
        usuario,
        libro,

        txtFechaSolicitarPrestamos.getText(),

        txtFechaLimiteSolicitarPrestamo.getText(),

        null,

        "PENDIENTE"
        );

        boolean registrado =
        prestamoDAO.registrarPrestamo(
                prestamo
        );

        if (registrado) {

        libroDAO.actualizarEstadoLibro(
            libro.getId(),
            "PRESTADO"
        );

        JOptionPane.showMessageDialog(
            this,
            "Préstamo registrado correctamente"
        );

        } else {

        JOptionPane.showMessageDialog(
            this,
            "Error al registrar préstamo"
        );
        }
    }//GEN-LAST:event_btnSolicitarPrestamoActionPerformed

    private void mostrarAyuda() {

    String contenido =
        "<html><body style='font-family:SansSerif; padding:8px'>"
        + "<h3 style='color:#2c6fad'> SOLICITAR PRÉSTAMO</h3>"
        + "<hr>"
        + "<p><b>Usuario</b> — Se carga automáticamente con tu nombre. "
        + "No es editable.</p>"
        + "<p><b>Libro</b> — Selecciona de la lista el libro que "
        + "deseas pedir prestado. Solo aparecen los libros DISPONIBLES.</p>"
        + "<p><b>Fecha Préstamo</b> — Fecha de hoy, asignada "
        + "automáticamente. No es editable.</p>"
        + "<p><b>Fecha Límite</b> — Fecha máxima de devolución "
        + "(20 días desde hoy). No es editable.</p>"
        + "<br>"
        + "<p>▶ Presiona <b>Solicitar Préstamo</b> para registrar tu solicitud.</p>"
        + "<br>"
        + "<p style='color:gray'> Recuerda devolver el libro antes "
        + "de la fecha límite para evitar mora.</p>"
        + "</body></html>";

    javax.swing.JLabel lbl = new javax.swing.JLabel(contenido);
    lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        lbl,
        "Ayuda — Solicitar Préstamo",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SolicitarPrestamoUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnSolicitarPrestamo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbLibroSolicitarPrestamo;
    private javax.swing.JLabel lblFechaLimiteSolicitar;
    private javax.swing.JLabel lblFechaSolicitarPrestamo;
    private javax.swing.JLabel lblLibroSolicitarPrestamo;
    private javax.swing.JLabel lblSolicitarPrestamoUsuario;
    private javax.swing.JLabel lblUsuarioSolicitarPrestamo;
    private javax.swing.JTextField txtFechaLimiteSolicitarPrestamo;
    private javax.swing.JTextField txtFechaSolicitarPrestamos;
    private javax.swing.JTextField txtUsuarioSolicitarPrestamos;
    // End of variables declaration//GEN-END:variables
}
